name: Create release assets

on:
  push:
    branches:
      - master
  release:
    types: [released]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          lfs: 'true'
      - name: upload assets
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'FINISHED/geopackages/*;FINISHED/*.csv'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          # To add assets to an existing release, use below line with release tag, then run action from actions page
          release-tag: v1.1.0
