name: Push previews.html to data repo

on: push

jobs:
  copy-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Pushes test file
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: './FINISHED/previews.html'
        destination_repo: 'DamonU2/data'
        destination_folder: '_pages/en/'
        user_email: 'damon_ulmi@hotmail.com'
        user_name: 'DamonU2'
        commit_message: 'Update to previews.html'
